import Head from 'next/head';

export default function SiteHead({ title }) {
  return (
    <Head>
      <title>{title} | The Parabole</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
