import Head from 'next/head';

export default function SiteHead({ title }) {
  const titleString = title + ' | The Parabole';

  return (
    <Head>
      <title>{titleString}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
